-- MySQL Script generated by MySQL Workbench
-- Fri Jan 27 21:36:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventoryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventoryDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventoryDB` DEFAULT CHARACTER SET utf8 ;
USE `inventoryDB` ;

-- -----------------------------------------------------
-- Table `inventoryDB`.`UserCredentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventoryDB`.`UserCredentials` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventoryDB`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventoryDB`.`Inventory` (
  `user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user`),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `inventoryDB`.`UserCredentials` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventoryDB`.`InventoryIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventoryDB`.`InventoryIngredient` (
  `name` VARCHAR(45) NOT NULL,
  `Inventory` VARCHAR(45) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  `measureUnit` VARCHAR(2) NULL,
  `expirationDate` DATE NULL,
  `notes` VARCHAR(200) NULL,
  PRIMARY KEY (`name`, `Inventory`),
  INDEX `inventory_idx` (`Inventory` ASC) VISIBLE,
  CONSTRAINT `inventory`
    FOREIGN KEY (`Inventory`)
    REFERENCES `inventoryDB`.`Inventory` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'admin';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
